test_that("handle_params", {
  expect_equal(handle_params(list()), list())
  x <- handle_params(list(hello = "world"), max_id = 1)
  expect_equal(x$hello, "world")
  expect_equal(x$max_id, 1)
  x <- handle_params(list(hello = "world"), max_id = 1, since_id = 2)
  expect_equal(x$hello, "world")
  expect_equal(x$max_id, 1)
  expect_equal(x$since_id, 2)
  x <- handle_params(list(hello = "world"), max_id = 1, min_id = 3)
  expect_equal(x$hello, "world")
  expect_equal(x$max_id, 1)
  expect_equal(x$min_id, 3)
  expect_null(x$since_id)
  ## positional
  x <- handle_params(list(hello = "world"), 1, 2)
  expect_equal(x$hello, "world")
  expect_equal(x$max_id, 1)
  expect_equal(x$since_id, 2)
  expect_null(x$min_id)
  x <- handle_params(list(hello = "world"), 1, 2, 3)
  expect_equal(x$hello, "world")
  expect_equal(x$max_id, 1)
  expect_equal(x$since_id, 2)
  expect_equal(x$min_id, 3)
})
